### ISSUE TITLE
Feature: 自动存储表情包

### ISSUE THREAD

**Issue by KomoriDev** [HuParry/nonebot-plugin-randpic#1]
自动存储表情包，随机自动发送。
就像酱紫
![栗子](https://github.com/HuParry/nonebot-plugin-randpic/assets/110453675/1c19d213-dffe-4f98-bfab-77c5be3b0f9c)

**Comment by HuParry** [comment]
你好，有添加表情包的功能，README里有写，你留意一下。

**Comment by HuParry** [comment]
添加<预设指令> ， 发送后bot会要你发对应表情包，你发送后就会保存。

**Comment by KomoriDev** [comment]
我的意思是Bot自动存储来着（

**Comment by KomoriDev** [comment]
我的意思是Bot自动存储来着（

**Comment by HuParry** [comment]
> 我的意思是Bot自动存储来着（

但是这个插件是支持多指令的，那你发的表情包应该存到哪个指令下呢？

自动存储很好搞，但是感觉对于这个插件来说不是很妥当.

**Comment by KomoriDev** [comment]
我理解了，感谢回复

**Comment by HuParry** [comment]
可以提出你的一些想法和建议，我很希望这个插件能有更加丰富的功能。

**Comment by KomoriDev** [comment]
再次感谢，不过我目前还没有新的想法（
这个 issue 我便先关闭了
