### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by MapleLeaf2007** [HuParry/nonebot-plugin-randpic#2]
可以添加一个发送**文件名**就发送对应图片的功能嘛？
或者是 **文件名_xxx**
发送 **文件名**
就随机在 **文件名_xxx** 里抽一个发送

**Comment by HuParry** [comment]
你所说的发送文件名是指发送图片的名字是吗？不过插件会统一修改所有图片的文件名。可以考虑在指令中加入序号，通过序号发送对应图片。
