### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by MapleLeaf2007** [HuParry/nonebot-plugin-randpic#3]
![37214bf9e2fa99adf19fb2d131063c1f](https://github.com/HuParry/nonebot-plugin-randpic/assets/122816807/443a48a6-9944-4ebb-bbd9-192848e5cc1c)

**Comment by HuParry** [comment]
目测是使用上有误，能给我看看QQ聊天界面的截图吗？尽量详细一点。

**Comment by MapleLeaf2007** [comment]
![image](https://github.com/HuParry/nonebot-plugin-randpic/assets/122816807/bf33b3ba-a9f8-4887-832a-599773f9e31b)

**Comment by HuParry** [comment]
感觉是适配器的原因，你知道怎么查看你的适配器版本吗？

**Comment by MapleLeaf2007** [comment]
用的是OneBot V11，昨天部署的，应该是最新版
再就是，我用的LLQQ的OneBotAPI插件
通过HTTP上报和gocq的反向ws连接的TRSS-Yunzai

**Comment by HuParry** [comment]
能看一下llqqnt发了什么过来吗？

**Comment by HuParry** [comment]
我看了下确实是没有 url 值，问了问几个开发者说在适配中。ws 连直接看的是没有url键值的。

后续我考虑换一个图片读取方式。

**Comment by MapleLeaf2007** [comment]
![image](https://github.com/HuParry/nonebot-plugin-randpic/assets/122816807/51c68bb1-104d-40b3-8db7-a636fc54f3e1)

**Comment by MapleLeaf2007** [comment]
QAQ，好的

**Comment by HuParry** [comment]
但是你这个把代码里的url改成http_file就行了，就报错的那里

**Comment by HuParry** [comment]
ob11的标准是传url，你这个是传了http_file，有些不同，不过其实相似。

**Comment by MapleLeaf2007** [comment]
好的！

**Comment by MapleLeaf2007** [comment]
![image](https://github.com/HuParry/nonebot-plugin-randpic/assets/122816807/a490877c-bfea-498b-968a-2741d96ceb9f)
是这个嘛？

**Comment by HuParry** [comment]
是的，你改成http_file

**Comment by MapleLeaf2007** [comment]
嗯嗯
