### ISSUE TITLE
消息合成失败，请查看日志或者检查输入

### ISSUE THREAD

**Issue by EisyMew** [HuParry/nonebot-plugin-randpic#4]
发送特定词汇时如图会发不出来
![屏幕截图 2024-03-23 114149](https://github.com/HuParry/nonebot-plugin-randpic/assets/107862925/544c3b5d-d798-4862-881a-fa7bc20508b3)
后端则提示
![屏幕截图 2024-03-23 114601](https://github.com/HuParry/nonebot-plugin-randpic/assets/107862925/0d62638e-0029-40e7-b9ad-011ea461ce8b)
用的nonebot+mumu模拟器的shamrock部署的，请问是什么原因导致的图片发不出来呢

**Comment by PioneerZHA** [comment]
同，一样的shamrock加mumu一样的报错

**Comment by HuParry** [comment]
可能是适配器的问题，由于我没使用过你们的部署方式，具体原因我也不太清楚。

如果可以的话，你可以尝试修改一下源码。
