### ISSUE TITLE
未来会支持批量上传嘛？（想提的需求有点多）

### ISSUE THREAD

**Issue by wuwangwo657** [HuParry/nonebot-plugin-randpic#5]
1、在实际使用中有时候需要批量上传图片，能否设置批量模式，在结束指令后再将中间发送的图片上传？

2、上传的权限能否添加额外设置白名单？因为群管理名额有上限。或者对某个文件夹的上传权限放开。

3、能否通过指令添加指令？有时候会想新建文件夹。

![ff8fb25b1b5937f622ef07f328e81662](https://github.com/HuParry/nonebot-plugin-randpic/assets/119086068/799d8627-10e1-45fe-9792-d54d2da2441f)

**Comment by HuParry** [comment]
你好：

1、关于批量导入图片，目前的想法是直接上传服务器。不过可以设计成在一个聊天框里塞多个图片（这样子的话可能得用电脑发送图片，因为移动端好像不能在一个聊天框里塞多个图片）。多条消息响应同一指令的话，我还没尝试过，不知道该怎么编写源码，可能需要请教一些大佬才能完成；

2、白名单功能可以考虑，因为如果允许所有人上传图片确实不太好；

3、通过指令添加指令，感觉有点难以实现。变量配置在 `.env` 文件中，似乎得对env文件进行读写，而且修改后得重启bot才会生效。有没有什么更好的办法呢？

感谢你提出的建议。

**Comment by wuwangwo657** [comment]
https://github.com/HibiKier/zhenxun_bot/blob/main/plugins/image_management/upload_image/__init__.py
之前有在真寻的功能里看到过连续上传图片的情况，其中也有新建分类的操作，不知道能否作为参考。
